#!/bin/sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 

export AWS_PROFILE=datanexus    # set this to the desired AWS profile in ~/.aws/credentials

if [ $# -eq 0 ] || [ "$1" == "-h" ] ; then
    echo "Usage:  `basename $0` [-h]\t\thelp"
    echo "\t`basename $0` [client-authentication] [aws | osp | FILE]\tuse aws, osp, or FILE configuration file"
    exit 0
fi

if [ ${2} == "aws" ] || [ ${2} == "osp" ]; then
  export configuration="$2-configuration.yml"
else
  export configuration="$2"
fi

./${1} -e "configuration=$configuration"
